CREATE TABLE [dbo].[Comments]
(
	[CommentID] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Text] VARCHAR(MAX) NOT NULL,
	[UserID] BIGINT NOT NULL,
	[Date] DATETIME NOT NULL CONSTRAINT [Comment_Date_Default] DEFAULT GETUTCDATE()
)


