/*
Deployment script for TestFaltaUno

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "TestFaltaUno"
:setvar DefaultFilePrefix "TestFaltaUno"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key 80e73452-63a5-4260-816b-f91d6c9b79a6 is skipped, element [dbo].[BaseUser].[Id] (SqlSimpleColumn) will not be renamed to UserID';


GO
PRINT N'Rename refactoring operation with key 93de9feb-9826-4398-b68d-8a3801340324, 521f7384-48fd-423f-907f-e9d637d7b2d9, 3a7aa2b1-6421-4427-9229-116f07610e5c is skipped, element [dbo].[Users].[Id] (SqlSimpleColumn) will not be renamed to ImplementationID';


GO
PRINT N'Rename refactoring operation with key 6eee8929-cc36-4332-a2f1-6d18553e7132 is skipped, element [dbo].[GeneralConfigurationParameters].[Id] (SqlSimpleColumn) will not be renamed to GeneralConfigurationParametersID';


GO
PRINT N'Rename refactoring operation with key 0a898e90-5542-4a56-b094-79e91dac0590 is skipped, element [dbo].[Implementations].[Id] (SqlSimpleColumn) will not be renamed to ImplementationID';


GO
PRINT N'Rename refactoring operation with key 660f6c18-0a1f-4fb7-8796-50cdc34cedba is skipped, element [dbo].[GeneralParameters].[GeneralParametersID] (SqlSimpleColumn) will not be renamed to GeneralParameterID';


GO
PRINT N'Rename refactoring operation with key be9685b4-8de8-4e4c-ae49-c33995fb3116, 91c06bdf-61f5-4339-8d15-0768117882ca is skipped, element [dbo].[Translations].[Id] (SqlSimpleColumn) will not be renamed to LanguageCode';


GO
PRINT N'Creating [dbo].[GeneralParameters]...';


GO
CREATE TABLE [dbo].[GeneralParameters] (
    [ImplementationID]   INT            NOT NULL,
    [GeneralParameterID] VARCHAR (255)  NOT NULL,
    [Type]               NVARCHAR (255) NOT NULL,
    [Value]              NVARCHAR (255) NOT NULL,
    PRIMARY KEY CLUSTERED ([GeneralParameterID] ASC, [ImplementationID] ASC)
);


GO
PRINT N'Creating [dbo].[Implementations]...';


GO
CREATE TABLE [dbo].[Implementations] (
    [ImplementationID] INT           NOT NULL,
    [Description]      VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ImplementationID] ASC)
);


GO
PRINT N'Creating [dbo].[LoginNames]...';


GO
CREATE TABLE [dbo].[LoginNames] (
    [LoginID]                    BIGINT        IDENTITY (1, 1) NOT NULL,
    [ImplementationID]           INT           NOT NULL,
    [UserID]                     BIGINT        NOT NULL,
    [LoginName]                  VARCHAR (255) NOT NULL,
    [Blocked]                    BIT           NULL,
    [Locked]                     BIT           NULL,
    [Deleted]                    BIT           NULL,
    [DateTimeCreated]            DATETIME      NOT NULL,
    [VerificationCode]           VARCHAR (255) NULL,
    [VerificationCodeExpiration] DATETIME      NULL,
    CONSTRAINT [PK_LoginNames] PRIMARY KEY CLUSTERED ([LoginID] DESC) ON [PRIMARY]
) ON [PRIMARY];


GO
PRINT N'Creating [dbo].[LoginNames].[IX_LoginNames]...';


GO
CREATE NONCLUSTERED INDEX [IX_LoginNames]
    ON [dbo].[LoginNames]([LoginName] ASC);


GO
PRINT N'Creating [dbo].[LoginPasswords]...';


GO
CREATE TABLE [dbo].[LoginPasswords] (
    [LoginID]  BIGINT        NOT NULL,
    [Password] VARCHAR (255) NOT NULL,
    [Sequence] TINYINT       NOT NULL,
    CONSTRAINT [PK_LoginPasswords] PRIMARY KEY CLUSTERED ([LoginID] DESC, [Password] ASC) ON [PRIMARY]
);


GO
PRINT N'Creating [dbo].[MailServerConfigurations]...';


GO
CREATE TABLE [dbo].[MailServerConfigurations] (
    [Name]                  VARCHAR (255) NOT NULL,
    [Subject]               VARCHAR (255) NULL,
    [Body]                  VARCHAR (MAX) NULL,
    [IsBodyHtml]            BIT           NULL,
    [Priority]              TINYINT       NULL,
    [From]                  VARCHAR (255) NOT NULL,
    [Host]                  VARCHAR (255) NOT NULL,
    [Port]                  INT           NULL,
    [EnableSsl]             BIT           NULL,
    [UseDefaultCredentials] BIT           NULL,
    [MailAddress]           VARCHAR (255) NOT NULL,
    [Password]              VARCHAR (255) NOT NULL,
    PRIMARY KEY CLUSTERED ([Name] ASC)
);


GO
PRINT N'Creating [dbo].[Sessions]...';


GO
CREATE TABLE [dbo].[Sessions] (
    [SessionID]          BIGINT        IDENTITY (1, 1) NOT NULL,
    [LoginID]            BIGINT        NOT NULL,
    [Session]            VARCHAR (255) NOT NULL,
    [DateTimeCreated]    DATETIME      NOT NULL,
    [DateTimeExpiration] DATETIME      NULL,
    [IP]                 VARCHAR (255) NULL,
    [UserAgent]          VARCHAR (255) NULL,
    CONSTRAINT [PK_Sessions] PRIMARY KEY CLUSTERED ([SessionID] ASC) ON [PRIMARY],
    UNIQUE NONCLUSTERED ([Session] ASC)
);


GO
PRINT N'Creating [dbo].[Sessions].[IX_Sessions_Session]...';


GO
CREATE NONCLUSTERED INDEX [IX_Sessions_Session]
    ON [dbo].[Sessions]([Session] ASC);


GO
PRINT N'Creating [dbo].[Translations]...';


GO
CREATE TABLE [dbo].[Translations] (
    [LanguageCode] CHAR (2)       NOT NULL,
    [Module]       NVARCHAR (60)  NOT NULL,
    [ConstantName] NVARCHAR (255) NOT NULL,
    [Translation]  VARCHAR (MAX)  NOT NULL,
    CONSTRAINT [PK_Translations] PRIMARY KEY CLUSTERED ([ConstantName] ASC, [Module] ASC, [LanguageCode] ASC)
);


GO
PRINT N'Creating [dbo].[UserIPAccessStatus]...';


GO
CREATE TABLE [dbo].[UserIPAccessStatus] (
    [ImplementationID] INT           NOT NULL,
    [UserID]           BIGINT        NOT NULL,
    [IP]               VARCHAR (255) NOT NULL,
    [Status]           INT           NOT NULL,
    [DateTimeCreated]  DATETIME      NOT NULL,
    CONSTRAINT [PK_UserIPAccessStatus] PRIMARY KEY CLUSTERED ([UserID] ASC)
) ON [PRIMARY];


GO
PRINT N'Creating [dbo].[Users]...';


GO
CREATE TABLE [dbo].[Users] (
    [UserID]           BIGINT        IDENTITY (1, 1) NOT NULL,
    [ImplementationID] INT           NOT NULL,
    [Name]             VARCHAR (255) NULL,
    [LastName]         VARCHAR (255) NULL,
    [DateTimeCreated]  DATETIME      NOT NULL,
    [Deleted]          BIT           NOT NULL,
    [DefaultLanguage]  VARCHAR (2)   NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([UserID] ASC)
);


GO
PRINT N'Creating unnamed constraint on [dbo].[GeneralParameters]...';


GO
ALTER TABLE [dbo].[GeneralParameters]
    ADD DEFAULT 0 FOR [ImplementationID];


GO
PRINT N'Creating unnamed constraint on [dbo].[LoginNames]...';


GO
ALTER TABLE [dbo].[LoginNames]
    ADD DEFAULT 0 FOR [ImplementationID];


GO
PRINT N'Creating unnamed constraint on [dbo].[LoginNames]...';


GO
ALTER TABLE [dbo].[LoginNames]
    ADD DEFAULT 0 FOR [Blocked];


GO
PRINT N'Creating unnamed constraint on [dbo].[LoginNames]...';


GO
ALTER TABLE [dbo].[LoginNames]
    ADD DEFAULT 0 FOR [Locked];


GO
PRINT N'Creating unnamed constraint on [dbo].[LoginNames]...';


GO
ALTER TABLE [dbo].[LoginNames]
    ADD DEFAULT 0 FOR [Deleted];


GO
PRINT N'Creating unnamed constraint on [dbo].[LoginNames]...';


GO
ALTER TABLE [dbo].[LoginNames]
    ADD DEFAULT GETUTCDATE() FOR [DateTimeCreated];


GO
PRINT N'Creating unnamed constraint on [dbo].[MailServerConfigurations]...';


GO
ALTER TABLE [dbo].[MailServerConfigurations]
    ADD DEFAULT '' FOR [Subject];


GO
PRINT N'Creating unnamed constraint on [dbo].[MailServerConfigurations]...';


GO
ALTER TABLE [dbo].[MailServerConfigurations]
    ADD DEFAULT '' FOR [Body];


GO
PRINT N'Creating unnamed constraint on [dbo].[MailServerConfigurations]...';


GO
ALTER TABLE [dbo].[MailServerConfigurations]
    ADD DEFAULT 1 FOR [IsBodyHtml];


GO
PRINT N'Creating unnamed constraint on [dbo].[MailServerConfigurations]...';


GO
ALTER TABLE [dbo].[MailServerConfigurations]
    ADD DEFAULT 0 FOR [Priority];


GO
PRINT N'Creating unnamed constraint on [dbo].[MailServerConfigurations]...';


GO
ALTER TABLE [dbo].[MailServerConfigurations]
    ADD DEFAULT 587 FOR [Port];


GO
PRINT N'Creating unnamed constraint on [dbo].[MailServerConfigurations]...';


GO
ALTER TABLE [dbo].[MailServerConfigurations]
    ADD DEFAULT 1 FOR [EnableSsl];


GO
PRINT N'Creating unnamed constraint on [dbo].[MailServerConfigurations]...';


GO
ALTER TABLE [dbo].[MailServerConfigurations]
    ADD DEFAULT 0 FOR [UseDefaultCredentials];


GO
PRINT N'Creating unnamed constraint on [dbo].[Sessions]...';


GO
ALTER TABLE [dbo].[Sessions]
    ADD DEFAULT GETUTCDATE() FOR [DateTimeCreated];


GO
PRINT N'Creating unnamed constraint on [dbo].[Translations]...';


GO
ALTER TABLE [dbo].[Translations]
    ADD DEFAULT '' FOR [Module];


GO
PRINT N'Creating unnamed constraint on [dbo].[UserIPAccessStatus]...';


GO
ALTER TABLE [dbo].[UserIPAccessStatus]
    ADD DEFAULT 0 FOR [ImplementationID];


GO
PRINT N'Creating unnamed constraint on [dbo].[UserIPAccessStatus]...';


GO
ALTER TABLE [dbo].[UserIPAccessStatus]
    ADD DEFAULT GETUTCDATE() FOR [DateTimeCreated];


GO
PRINT N'Creating unnamed constraint on [dbo].[Users]...';


GO
ALTER TABLE [dbo].[Users]
    ADD DEFAULT 0 FOR [ImplementationID];


GO
PRINT N'Creating unnamed constraint on [dbo].[Users]...';


GO
ALTER TABLE [dbo].[Users]
    ADD DEFAULT GETUTCDATE() FOR [DateTimeCreated];


GO
PRINT N'Creating unnamed constraint on [dbo].[Users]...';


GO
ALTER TABLE [dbo].[Users]
    ADD DEFAULT 0 FOR [Deleted];


GO
PRINT N'Creating [dbo].[FK_GeneralParameters_Implementations_ImplementationID]...';


GO
ALTER TABLE [dbo].[GeneralParameters] WITH NOCHECK
    ADD CONSTRAINT [FK_GeneralParameters_Implementations_ImplementationID] FOREIGN KEY ([ImplementationID]) REFERENCES [dbo].[Implementations] ([ImplementationID]);


GO
PRINT N'Creating [dbo].[FK_LoginNames_Users_UserID]...';


GO
ALTER TABLE [dbo].[LoginNames] WITH NOCHECK
    ADD CONSTRAINT [FK_LoginNames_Users_UserID] FOREIGN KEY ([UserID]) REFERENCES [dbo].[Users] ([UserID]);


GO
PRINT N'Creating [dbo].[FK_LoginNames_Implementations_ImplementationID]...';


GO
ALTER TABLE [dbo].[LoginNames] WITH NOCHECK
    ADD CONSTRAINT [FK_LoginNames_Implementations_ImplementationID] FOREIGN KEY ([ImplementationID]) REFERENCES [dbo].[Implementations] ([ImplementationID]);


GO
PRINT N'Creating [dbo].[FK_LoginPasswords_LoginNames_LoginID]...';


GO
ALTER TABLE [dbo].[LoginPasswords] WITH NOCHECK
    ADD CONSTRAINT [FK_LoginPasswords_LoginNames_LoginID] FOREIGN KEY ([LoginID]) REFERENCES [dbo].[LoginNames] ([LoginID]);


GO
PRINT N'Creating [dbo].[FK_Sessions_LoginNames_LoginID]...';


GO
ALTER TABLE [dbo].[Sessions] WITH NOCHECK
    ADD CONSTRAINT [FK_Sessions_LoginNames_LoginID] FOREIGN KEY ([LoginID]) REFERENCES [dbo].[LoginNames] ([LoginID]);


GO
PRINT N'Creating [dbo].[FK_UserIPAccessStatus_Users_UserID]...';


GO
ALTER TABLE [dbo].[UserIPAccessStatus] WITH NOCHECK
    ADD CONSTRAINT [FK_UserIPAccessStatus_Users_UserID] FOREIGN KEY ([UserID]) REFERENCES [dbo].[Users] ([UserID]);


GO
PRINT N'Creating [dbo].[FK_UserIPAccessStatus_USers_ImplementationID]...';


GO
ALTER TABLE [dbo].[UserIPAccessStatus] WITH NOCHECK
    ADD CONSTRAINT [FK_UserIPAccessStatus_USers_ImplementationID] FOREIGN KEY ([ImplementationID]) REFERENCES [dbo].[Implementations] ([ImplementationID]);


GO
PRINT N'Altering [dbo].[GetTranslations]...';


GO
ALTER PROCEDURE [dbo].[GetTranslations]
AS
BEGIN
	SELECT
		LanguageCode,
		Module,
		ConstantName,
		Translation
	FROM 
		Translations
END
GO
PRINT N'Creating [dbo].[GetMailServerConfiguration]...';


GO
CREATE PROCEDURE [dbo].[GetMailServerConfiguration]
AS
	SELECT 
		[Name],
		[Subject],
		[Body],
		[IsBodyHtml],
		[Priority],
		[From],
		[Host],
		[Port],
		[EnableSsl] ,
		[UseDefaultCredentials],
		[MailAddress],
		[Password]
	FROM
		[MailServerConfigurations]
GO
-- Refactoring step to update target server with deployed transaction logs

IF OBJECT_ID(N'dbo.__RefactorLog') IS NULL
BEGIN
    CREATE TABLE [dbo].[__RefactorLog] (OperationKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY)
    EXEC sp_addextendedproperty N'microsoft_database_tools_support', N'refactoring log', N'schema', N'dbo', N'table', N'__RefactorLog'
END
GO
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '80e73452-63a5-4260-816b-f91d6c9b79a6')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('80e73452-63a5-4260-816b-f91d6c9b79a6')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '93de9feb-9826-4398-b68d-8a3801340324')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('93de9feb-9826-4398-b68d-8a3801340324')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '521f7384-48fd-423f-907f-e9d637d7b2d9')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('521f7384-48fd-423f-907f-e9d637d7b2d9')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '3a7aa2b1-6421-4427-9229-116f07610e5c')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('3a7aa2b1-6421-4427-9229-116f07610e5c')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '6eee8929-cc36-4332-a2f1-6d18553e7132')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('6eee8929-cc36-4332-a2f1-6d18553e7132')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '0a898e90-5542-4a56-b094-79e91dac0590')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('0a898e90-5542-4a56-b094-79e91dac0590')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '660f6c18-0a1f-4fb7-8796-50cdc34cedba')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('660f6c18-0a1f-4fb7-8796-50cdc34cedba')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'be9685b4-8de8-4e4c-ae49-c33995fb3116')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('be9685b4-8de8-4e4c-ae49-c33995fb3116')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '91c06bdf-61f5-4339-8d15-0768117882ca')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('91c06bdf-61f5-4339-8d15-0768117882ca')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '08f9e289-06c0-4563-9cc9-5548905712cc')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('08f9e289-06c0-4563-9cc9-5548905712cc')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '9392da0c-1a7c-4c66-84bf-d82226fb1337')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('9392da0c-1a7c-4c66-84bf-d82226fb1337')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[GeneralParameters] WITH CHECK CHECK CONSTRAINT [FK_GeneralParameters_Implementations_ImplementationID];

ALTER TABLE [dbo].[LoginNames] WITH CHECK CHECK CONSTRAINT [FK_LoginNames_Users_UserID];

ALTER TABLE [dbo].[LoginNames] WITH CHECK CHECK CONSTRAINT [FK_LoginNames_Implementations_ImplementationID];

ALTER TABLE [dbo].[LoginPasswords] WITH CHECK CHECK CONSTRAINT [FK_LoginPasswords_LoginNames_LoginID];

ALTER TABLE [dbo].[Sessions] WITH CHECK CHECK CONSTRAINT [FK_Sessions_LoginNames_LoginID];

ALTER TABLE [dbo].[UserIPAccessStatus] WITH CHECK CHECK CONSTRAINT [FK_UserIPAccessStatus_Users_UserID];

ALTER TABLE [dbo].[UserIPAccessStatus] WITH CHECK CHECK CONSTRAINT [FK_UserIPAccessStatus_USers_ImplementationID];


GO
PRINT N'Update complete.';


GO
